src/scm/plams/tools/ase.py
Hey,
I wrote two small functions to convert ASE Atoms objects to PLAMS Molecule objects and vice versa. They are very similar, so there is no big problem.
Since the extended XYZ format of ASE and the SCM-XYZ format are not compatible this makes the integration of workflows with PLAMS and ASE and their related codes easier and it is less code then to write a file-converter.
Right now only atomic numbers (symbols are linked in both modules), coordinates and lattice vectors are converted, the atom ordering is preserved.
Hope this helps someone else too.
Patrick
=> ASE Atoms - PLAMS Molecule Interface

src/scm/plams/tools/ase.py
Previous behavior would yield wrong results in 1D and 2D molecules or just crash if molecule.lattice is shorter then 3x3. Depending on the way the PLAMS Molecule is made, the lattice can actually be shorter than 3x3. This case did not appear in my test cases, now I stumbled upon it.
=> Fixed issue of 1D and 2D lattice vectors in tools.ase

src/scm/plams/core/basemol.py, src/scm/plams/interfaces/adfsuite/ams.py
The `read_molecule` method  was returning a `Molecule` object with atomic coordinates in angstrom and lattice vectors in bohr.
=>  BugFix in plams-ams interface: inconsistent units between atomic and lattice vector coords

src/scm/plams/tools/kftools.py
Sadly, our license prints an Umlaut "ä" (0xe4) to the kf files. On some systems this causes a crash of the KFReader like this:
>   File "/home/patrickm/git/myPlamsFork/src/scm/plams/tools/kftools.py", line 73, in read
ret = self._get_data(self._read_block(f,i))[vtype-1][vstart-1:]
File "/home/patrickm/git/myPlamsFork/src/scm/plams/tools/kftools.py", line 150, in _get_data
contents = self._parse(datablock[hlen:], zip((i,d,s,b),(self.word,'d','s',self.word)))
File "/home/patrickm/git/myPlamsFork/src/scm/plams/tools/kftools.py", line 139, in _parse
new = tuple(map(lambda x: x.decode() if isinstance(x,bytes) else x, new))
File "/home/patrickm/git/myPlamsFork/src/scm/plams/tools/kftools.py", line 139, in <lambda>
new = tuple(map(lambda x: x.decode() if isinstance(x,bytes) else x, new)) …
=> BUG: KFReader crashes if German umlaut in kf-file

tools/kftools.py
These changes eliminate two main sources of unnecessary overhead in KFReader:
- `_parse` used to do an isinstance(bytes) check on every single value (which are mostly floats). It also expensively decoded all strings, no matter if the caller was interested in them or not. Apart from being super slow, this also broke completely when there were any multibyte characters in the KF file. KF variable lengths are stored in bytes, not characters, so the data extraction/cutting needs to be done before decoding.
- `_datablocks` used to waste time creating a list of all logical block indices every time it was called.
Together, these changes make KFReader about 10x faster when processing common MD trajectories.
=> Speed up KFReader on larger files and fix Unicode support

doc/source/conf.py, doc/source/interfaces/cp2k.rst, interfaces/thirdparty/cp2k.py
Hey,
sorry for the MR-Spam. I remembered yesterday evening that some sections will make trouble loading. So this MR should allow loading of restart files printed by CP2K. Including sections like *VELOCITY*, *COORD* and *FORCE*.
Also one can now build a molecule from such loaded restart files using `Cp2kSettings2Mol`.
Cheers,
Patrick
=> Enhancement and new features for CP2K interface

interfaces/adfsuite/ams.py
[get_frequencies](https://github.com/SCM-NV/PLAMS/blob/282776d40e0f23b0e6b1758ef7feeeae6c60284e/interfaces/adfsuite/ams.py#L215) was mistakenly trying to pull vibrational frequencies from the AMSResults section instead of the Vibrations section. This has now been fixed.
=> Bug fix: get_frequencies() now correctly points to the 'Vibrations' section

mol/bond.py
The [`Bond.resize()`](https://github.com/SCM-NV/PLAMS/blob/098bd207ad5d9a68bb97fa0a3266f1586900961a/mol/bond.py#L94) method was referring to an undefined variable by the name of `bond` (which should've been `self`).
=> Bug fix: name 'bond' is not defined

mol/molecule.py
* [`Molecule.as_array()`](https://github.com/SCM-NV/PLAMS/blob/75127bb74af4a3365f884fcdb54931ac21138933/mol/molecule.py#L1231) has been made 10-20% faster. No caveats here, it's now just plain faster.
* [`Molecule.__getitem__()`](https://github.com/SCM-NV/PLAMS/blob/75127bb74af4a3365f884fcdb54931ac21138933/mol/molecule.py#L1125) now checks for the `__index__()` method rather than [`int`](https://docs.python.org/3/library/functions.html#int) instances; see [PEP 357](https://www.python.org/dev/peps/pep-0357/). 
Most importantly, this allows one to use instances of `np.integer` for slicing without having to convert it into a (builtin) integer every single time.
* Exchanged a number of explicit instance checks with duck typing-based approaches. For example: checking for an iterable of length …
=> Molecule() update

interfaces/molecule/rdkit.py
The [``add_Hs()``](https://www.scm.com/doc/plams/components/mol_rdkit.html#scm.plams.interfaces.molecule.rdkit.add_Hs) function has the occasionally causes segmentation fault, hard-crashing python in the process. This bug fix addresses the issue by verifying that ``ResInfo is not None`` before continuing.
=> Prevent segmentation faults in ``add_Hs()``

mol/molecule.py
[``Molecule.read()``](https://www.scm.com/doc/plams/components/mol_api.html#scm.plams.mol.molecule.Molecule.read) and [``Molecule.write()``](https://www.scm.com/doc/plams/components/mol_api.html#scm.plams.mol.molecule.Molecule.write) can now accept any [path-like object](https://docs.python.org/3.8/glossary.html#term-path-like-object) and not just strings. Compatibility with the builtin [pathlib](https://docs.python.org/3/library/pathlib.html#module-pathlib) module would be the main advantage of the proposed changes.
=> Ensure that Molecule.read() and Molecule.write() can handle PathLike objects

interfaces/adfsuite/crs.py
* Ensure that ``CRSResults.section`` is always capitalized just like in the .coskf file.
* Fixed an incorrect section name in [``CRSResults.get_activity_coefficient()``](https://www.scm.com/doc/plams/interfaces/crs.html#scm.plams.interfaces.adfsuite.crs.CRSResults.get_activity_coefficient).
* Cache the to-be reutrned value of ``CRSResults.section`` for future use.
* Added a couple of missing type hints.
=> CRSResults: 2 bug fixes and 2 improvements

core/settings.py
So yeah, ``Settings.find_case()`` is still broken.
``Settings.find_case()`` currently assumes that ALL keys in ``self`` are strings in the following part of the code.
``` python
for k in self:
if k.lower() == lowkey:  # will crash if *k* is not a string
return k
```
Added a ``try`` / ``except`` clause for to prevent exceptions in the following two cases:
* A key does not have the ``.lower`` attribute (_e.g._ ``k`` is not a string; raises a ``AttributeError``).
* The ``k.lower`` attribute is not callable (raises a ``TypeError``).
=> Fixed an issue where Settings.find_case() could raise an AttributeError or TypeError

interfaces/thirdparty/cp2k.py
=> Use srun by default in CP2K

interfaces/molecule/rdkit.py
Previously the `readpdb()` and `writepdb()` could take either a string or file-like object as argument.
The scope of the former type has been expanded; both functions can now take any [path-like](https://docs.python.org/3/glossary.html#term-path-like-object) object as argument.
=> Allow `readpdb()` and `writepdb()` to take any path-like object

interfaces/thirdparty/crystal.py
My Crystal interface throws an error when passing non-strings to an ordered (e.g. `settings.input.options.asdf._1`) input section, because I was calling `upper()` on them.
Fixed this by converting list elements and single elements to strings before using `.upper()`.
While doing this, I also noticed that lists were not handled properly due to wrong ordering of the `elif` statements. Fixed that.
Btw: Is there some testing suite that I could use when contributing in the future? Till now I only run my private tests... Could prevent small things like this one.
=> Crystal: Fix Input Error in Ordered Input Sections

interfaces/adfsuite/adf.py, tools/periodic_table.py
Loading an ADF job with ghost atoms (e.g. `Gh.C`) is not working, because the periodic table module does not support ghosted atoms. I hacked an `elif` clause. I think it is the best way to go, even though the elements are lost this way (replaced by `Xx`, the standard PLAMS special atom).
Passing the element would end up with a complete molecule, which is I think much more prone to misinterpretation.
=> FIX: Loading a Job with Ghost Atoms

core/settings.py
Quite recently the ``Settings.__init__()`` method was updated to check for the presence of (nested) ``Settings`` instances before calling the (recursive) constructor.
```python
def __init__(self, *args, **kwargs):
...
for k,v in self.items():
if isinstance(v, dict) and not isinstance(v, Settings):  # This line
...
```
However, the current implementation has the unintended side-effect that ``Settings`` subclass can no longer be properly converted into ``Settings`` and _vice versa_, as all subclass instances are also instances ``Settings``. 
Note that this issue only applies to nested settings (which, let's be honest, includes most instances).
```python
from scm.plams import Settings
class SubClass(Settings): ...
s_sub = SubClass()
s_sub.a.b.c.d = True
s = Settings(s_sub)
type(s)
<class …
```
=> Fixed an issue where Settings subclasses could not be converted into Settings and vice versa

interfaces/adfsuite/adf.py
The `ADFResults.get_energy_decomposition` method claimed to get all contributions of the total bonding energy. If using a dispersion correction scheme (I only tested D3 variants), an additional entry is found in the KF file. Without this, the sum of the returned values is not equal to the total bonding energy.
This is a one-line change so far, as I am not sure what else might contribute to the total bonding energy. Perhaps there is some internal documentation where someone could look this up or check the ADF code directly?
Not sure how this will be affected by the shift to the AMS engine, but right now all KF files I found have this. So at least for usability with the current release I suggest to add all additional energy terms in such `if` clauses.
=> ADFResults: Energy Contributions

core/settings.py
This PR makes two enhancements to the `Settings` class:
* It adds support for case-insensitivity to three more methods: `get`, `pop` and `popitem`.
* It adds support for `Settings` subclasses to all remaining methods.
=> Add more `Settings` support for subclasses and case-insensitivity

interfaces/thirdparty/cp2k.py
`Cp2kResults.get_hirshfeld_charges(return_spin=True)` fails because there is an empty line in the CP2K output of the version I am using right now. Small fix prevents that from happening.
=> Fix CP2KResults._get_charges with Empty Lines

core/functions.py, core/results.py, doc/source/cookbook/numhess.rst, examples/ExcitationsWorkflow.py, interfaces/adfsuite/ams.py, interfaces/adfsuite/crs.py, interfaces/molecule/rdkit.py, interfaces/thirdparty/cp2k.py, interfaces/thirdparty/crystal.py, mol/molecule.py, mol/pdbtools.py, recipes/vibration.py, trajectories/rkffile.py
This fixes #107 .
I've run a linter to catch non-standard uses of comparison operators.
Changes that have been made:
* Comparisons to True, False and None have all been changed to use the `is`
operator
* Comparisons to string literals have all been changed to use the `==`
oeprator
* Comparison to the empty list has been replaced with simply if my_list:
(which saves instantiating an empty list each time).
* Range comparisons (e.g. `if a < b and a > c`) have been changed to the
more standard `if c < a < b`.
I also caught one error in the numhess.rst which just required the
addition of a blank line to complete a code block so I've included it
here.
=> Fixed non-standard use of comparison operators

tools/units.py
Unit conversions have become a major bottleneck recently as new units are added. These two simple patches bring the time to create 10000 Atoms() with coordinates in a.u. down from 6 seconds to 300 ms. Everything seems to be working exactly the same way as before (including error messages for mismatched units), with the exception of conversions from "someInvalidUnit" to "someInvalidUnit", which used to fail but now silently succeed. I hope that's not a big issue.
=> Speed up unit conversions

interfaces/adfsuite/unifac.py, interfaces/molecule/packmol.py, recipes/adfcosmorscompound.py, recipes/redox.py
**Description**
This is a manual sync of commits from subversion `fix2024` branch, from `2024.101`  to `2024.102` (07/06/2024) tags.
This will be merged into the `fix2024` branch here.
**Notes for Reviewer**
The copied files have been checked by comparing the commits to the subversion equivalent, by using:
git diff --shortstat <2024.101> <2024.102>
4 files changed, 64 insertions(+), 44 deletions(-)
Please could the reviewer double check that the commits align with what they would expect from subversion.
**List of contained Commits**
syncing the following commits:
Matti Hellström: fix AMSRedoxScreeningJob SO103 SCMSUITE-9508 
Matti Hellström: catch SystemError in unifac.py to allow users to copy scm into other Python envs SO-- 
Matti Hellström: plams packmol allow small noise in lattice …
=> Manual sync from SCM-svn to GitHub from 2024.101 to 2024.102
